# Generated by Django 4.0.4 on 2022-06-08 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_dob_touristuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='TDSUser',
        ),
        migrations.DeleteModel(
            name='TDType',
        ),
        migrations.DeleteModel(
            name='TouristUser',
        ),
    ]
