# Generated by Django 4.0.4 on 2022-06-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TDSManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdtype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
