# Generated by Django 4.0.4 on 2022-06-08 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TDSManager', '0002_alter_tdtype_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdsuser',
            name='tdid',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tdsuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tds', to=settings.AUTH_USER_MODEL),
        ),
    ]
