# Generated by Django 4.0.4 on 2022-06-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TDSManager', '0005_announcements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
