# Generated by Django 4.0.4 on 2022-06-09 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TDSManager', '0006_alter_announcements_id'),
        ('TouristUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('vaccination_status', models.CharField(blank=True, max_length=100, null=True)),
                ('vaccination_certificate', models.FileField(blank=True, default='images/default.jpg', null=True, upload_to='vaccination/')),
                ('tuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TouristUser.touristuser')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketid', models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False)),
                ('no_of_Tickets', models.IntegerField(default=0)),
                ('no_of_adults', models.IntegerField(default=0)),
                ('no_of_children', models.IntegerField(default=0)),
                ('total_price', models.FloatField(default=0.0)),
                ('booked_date', models.DateField(auto_now_add=True)),
                ('booking_date', models.DateField()),
                ('group_image', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='groupimg/')),
                ('tds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TDSManager.tdsuser')),
                ('team_members', models.ManyToManyField(blank=True, related_name='team_members', to='TouristUser.teammember')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TouristUser.touristuser')),
            ],
        ),
    ]
