# Generated by Django 4.0.4 on 2022-06-09 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TouristUser', '0002_teammember_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='booking_date',
            new_name='visiting_date',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='tuser',
        ),
    ]
